CREATE OR REPLACE TABLE MOTORCOLLISION.MOTORTEST.DIM_VICTIM AS
SELECT 
    '1' AS VICTIM_ID, -- Unique identifier for pedestrians
    'Pedestrian' AS VICTIM_TYPE,
    'NUMBER_OF_PEDESTRIANS_INJURED' AS INJURED_COLUMN,
    'NUMBER_OF_PEDESTRIANS_KILLED' AS KILLED_COLUMN
UNION ALL
SELECT 
    '2' AS VICTIM_ID, -- Unique identifier for cyclists
    'Cyclist' AS VICTIM_TYPE,
    'NUMBER_OF_CYCLIST_INJURED' AS INJURED_COLUMN,
    'NUMBER_OF_CYCLIST_KILLED' AS KILLED_COLUMN
UNION ALL
SELECT 
    '3' AS VICTIM_ID, -- Unique identifier for motorists
    'Motorist' AS VICTIM_TYPE,
    'NUMBER_OF_MOTORIST_INJURED' AS INJURED_COLUMN,
    'NUMBER_OF_MOTORIST_KILLED' AS KILLED_COLUMN
UNION ALL
SELECT 
    '4' AS VICTIM_ID, -- Unique identifier for all persons
    'Total' AS VICTIM_TYPE,
    'NUMBER_OF_PERSONS_INJURED' AS INJURED_COLUMN,
    'NUMBER_OF_PERSONS_KILLED' AS KILLED_COLUMN;
