CREATE OR REPLACE TABLE MOTORCOLLISION.MOTORTEST.DIM_DATE AS
SELECT 
    DISTINCT
    CRASH_DATE AS DATE_ID, -- Unique date identifier
    YEAR(CRASH_DATE) AS YEAR,
    MONTH(CRASH_DATE) AS MONTH,
    DAY(CRASH_DATE) AS DAY,
    DAYNAME(CRASH_DATE) AS DAY_OF_WEEK,
    CRASH_TIME AS TIME_OF_DAY -- Crash time for granular analysis
FROM MOTORCOLLISION.MOTORTEST.RAW_MOTOR
WHERE CRASH_DATE IS NOT NULL;
