CREATE OR REPLACE TABLE MOTORCOLLISION.MOTORTEST.DIM_FACTORS AS
SELECT 
    MD5(CONCAT(
        COALESCE(CONTRIBUTING_FACTOR_VEHICLE_1, ''), 
        COALESCE(CONTRIBUTING_FACTOR_VEHICLE_2, ''), 
        COALESCE(CONTRIBUTING_FACTOR_VEHICLE_3, ''), 
        COALESCE(CONTRIBUTING_FACTOR_VEHICLE_4, ''), 
        COALESCE(CONTRIBUTING_FACTOR_VEHICLE_5, '')
    )) AS FACTOR_ID, -- Unique ID for each combination of contributing factors
    CONTRIBUTING_FACTOR_VEHICLE_1,
    CONTRIBUTING_FACTOR_VEHICLE_2,
    CONTRIBUTING_FACTOR_VEHICLE_3,
    CONTRIBUTING_FACTOR_VEHICLE_4,
    CONTRIBUTING_FACTOR_VEHICLE_5
FROM MOTORCOLLISION.MOTORTEST.RAW_MOTOR
WHERE CONTRIBUTING_FACTOR_VEHICLE_1 IS NOT NULL;
